### ISSUE TITLE
Is this project working?

### ISSUE THREAD

**Issue by MaxGabriel** [carymrobbins/yesod-js-routes#1]

**Comment by carymrobbins** [comment]
I made this a while back for a specific use case, although I'm not sure if it works with the current version of yesod.

**Comment by MaxGabriel** [comment]
Hey, my apologies on such a bad issue—I pressed the enter key and submitted it before I wrote anything.

It does look to be working, as it happens!

**Comment by carymrobbins** [comment]
@MaxGabriel - No problem at all!  Feel free to fork or submit PRs, I haven't messed with this in quite some time.  It's all pretty straightforward.

**Comment by MaxGabriel** [comment]
Thanks for making this package! I answered [the question](http://stackoverflow.com/questions/35756020/yesod-parametric-handler-in-julius-templates/35759735#35759735) with it, hope it turns out to be helpful for them
